name: sport_defi_app
description: "Une application de suivi de dÃ©fis sportifs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - images/sq.jpg
    - images/courir.jpg
    - images/defit3.jpeg
    - images/defit4.jpg
    - images/defit5.jpg
    - images/defit6.jpg
    - images/defis7.jpg
    - images/background.png
    - images/logo.png